### ISSUE TITLE
reporting bug

### ISSUE THREAD

**Issue by jhumann** [BrendelGroup/AEGeAn#186] opened 2017-08-23 21:22 UTC
I was comparing 2 annotations and received some warnings for genes with invalid mRNAs, and then the program stopped with this info: 
Assertion failed: (agn_typecheck_gene(fn)), function gene_stream_next, file src/core/AgnGeneStream.c, line 225.
This is a bug, please report it at https://github.com/standage/AEGeAn/issues.

**Comment by standage** [comment] 2017-08-23 21:24
Thanks for the report! Could you please provide the two files you are comparing, as well as the command you executed? Alternatively, a subset of each the two files that replicates the error would be sufficient.

**Comment by jhumann** [comment] 2017-08-24 18:26
the reference file: 
[ncbi_riceChr1_renamedSeq4-forParseval2.txt](https://github.com/BrendelGroup/AEGeAn/files/1249863/ncbi_riceChr1_renamedSeq4-forParseval2.txt)

the prediction file:
[t_5948198d65ceb-599f04d1caf48-gff3_gene_prediction.gensas.gff3.txt](https://github.com/BrendelGroup/AEGeAn/files/1249866/t_5948198d65ceb-599f04d1caf48-gff3_gene_prediction.gensas.gff3.txt)

command: /usr/local/AEGeAn/bin/parseval -o RiceNCBIvSNAP -s -w ../Rice_chr1/ncbi_riceChr1_renamedSeq4-forParseval2.txt Rice_chr1-SNAP/t_5948198d65ceb-599f04d1caf48-gff3_gene_prediction.gensas.gff3.txt

I appreciate the help!

**Comment by standage** [comment] 2017-08-28 20:00
Thanks for sharing your files. I've been able to reproduce the error you reported, but I have not yet been able to isolate the cause.

In examining the data, I noticed that the "NCBI" file (labelled DDBJ internally) does not follow the annotation convention required in the [ParsEval documentation](http://aegean.readthedocs.io/en/stable/parseval.html): specifically, that isoforms be declared using features of type `mRNA`. I don't know if this is the *direct* cause of the bug we are seeing, but it is likely a contributing factor.

If you can address this issue, I'd be happy to re-evaluate. Let me know if you have any trouble or if anything is unclear.

**Comment by standage** [comment] 2018-02-27 23:36
Closing this thread now. Feel free to re-open if you need further assistance.

**Closed by standage** 2018-02-27 23:36 UTC
